
db10 = @(x) 10 .* log10( x );

[ x2 , y2 , w2 ] = ffImportEnergyDensity2D( 'w.dat' );
xx = squeeze( x2(:,1) );
yy = squeeze( y2(1,:) );
Nx = length( xx );
Ny = length( yy );

[ x2J , y2J , J2x , J2y ] = ffImportEnergyDensityFlux2D( 'J.dat' );

plotHeatMap( x2 , y2, db10(3e8.*w2) , ...
             0.0 , 0.9 , '{/Helvetica-Italic x} (m)' , ...
             0.0 , 0.45 , '{/Helvetica-Italic y} (m)' , ...
             12 , 22 , '{/Helvetica-Italic S} (dB W/m^2)' , 'plotHeatMap' );
       
plotContourMap( x2 , y2, db10(3e8.*w2) , ...
                0.0 , 0.9 , '{/Helvetica-Italic x} (m)' , ...
                0.0 , 0.45 , '{/Helvetica-Italic y} (m)' , ...
                12 , 22 , '{/Helvetica-Italic S} (dB W/m^2)' , [ 13.5 14 , 15 , 16 ,17 , 24 , 24.5 ] , 'plotContourMap' );
      
plotContourHeatMap( x2 , y2, db10(3e8.*w2) , ...
                    0.0 , 0.9 , '{/Helvetica-Italic x} (m)' , ...
                    0.0 , 0.45 , '{/Helvetica-Italic y} (m)' , ...
                    12 , 22 , '{/Helvetica-Italic S} (dB W/m^2)' , [ 13.5 14 , 15 , 16 ,17 , 24 , 24.5 ] , 'plotContourHeatMap' );

plotVectorMap( x2J , y2J, J2x , J2y , ...
               0.0 , 0.9 , '{/Helvetica-Italic x} (m)' , ...
               0.0 , 0.45 , '{/Helvetica-Italic y} (m)' , ...
               [] , [] , '{/Helvetica-Bold-Italic J} (dB W/m^2)' , 'plotVectorMap' );

plotVectorHeatMap( x2J , y2J, J2x , J2y , ...
                   0.0 , 0.9 , '{/Helvetica-Italic x} (m)' , ...
                   0.0 , 0.45 , '{/Helvetica-Italic y} (m)' , ...
                   [] , [] , '{/Helvetica-Bold-Italic J} (dB W/m^2)' , 'plotVectorHeatMap' );
                  